### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by josebalius** [nikmartin/nikmartin.github.io#1]
Hey man,

Just trying to get in touch with you, I saw you had published a qbwc npm module and it is not unpublished, do you have any plans to republish it in the future?

Thanks!

Jose

**Comment by nikmartin** [comment]
No, that project no longer exists as the company I was working for that wanted to do this imploded so I no longer work for them. I recently removed this project from npm. There was no actual code yet, just some documentation.
